### ISSUE TITLE
 How about align o.at(expr) with o[expr]？

### ISSUE THREAD

**Issue by zeldajay** [tc39/proposal-relative-indexing-method#42]
Refactoring Hazard, people can't directly replace the [] in the old code.

**Comment by septs** [comment]
https://github.com/hax/proposal-index-from-end

**Comment by nicolo-ribaudo** [comment]
If `o.at(expr)` becomes the same as `o[expr]`, then there is no reason to adopt this proposal: it would just add another (slightly slower and longer to type) way of doing something that is already supported by syntax.

**Comment by syg** [comment]
Thanks for the comment. Directly replacing `[]` is not the use case: it is not possible to do relative indexing via `[]` now, so I'm not sure what the refactoring hazard is. Additional syntax for relative indexing is a different proposal altogether -- and does not really obviate the need for serving the use case via this method.

Closing for now.
