### ISSUE TITLE
Assignability

### ISSUE THREAD

**Issue by falsandtru** [tc39/proposal-relative-indexing-method#45]
Does `.at` method have ability to assign a new value like `arr.at(-1) = 0`? Or can you enable `arr.at[-1] = 0`?

**Comment by ljharb** [comment]
No, it doesn’t, and no, we can’t; JS doesn’t have “functions return assignable references” as a feature (imo, thankfully).

**Comment by falsandtru** [comment]
I think the expected feature is a readable and writable accessor. But this proposal doesn't aim at updating an element via negative index?

**Comment by ljharb** [comment]
Correct, it is only for reading the value.

**Comment by falsandtru** [comment]
I see, thanks.
